# Explicit CPU graph for the scene-driven demo. Renderer integration follows.
include("${CMAKE_CURRENT_LIST_DIR}/NauMinimalRuntime.cmake")
set(NAU_FRAMEWORK_TARGET NauFrameworkDemo)
set(NAU_MINIMAL_MODULE_DIRS platform_app assets scene assets_cpu)
if(EMSCRIPTEN)
  execute_process(COMMAND "${CMAKE_CXX_COMPILER}" --version
    OUTPUT_VARIABLE demoCompilerVersion ERROR_VARIABLE demoCompilerError RESULT_VARIABLE demoCompilerResult)
  if(NOT demoCompilerResult EQUAL 0 OR NOT demoCompilerVersion MATCHES "6\\.0\\.9[ \r\n]")
    message(FATAL_ERROR "NauDemo browser requires Emscripten SDK 6.0.9. Install/activate 6.0.9 explicitly and load emsdk_env.ps1 before configuring.")
  endif()
  list(APPEND NAU_MINIMAL_MODULE_DIRS browser_renderer)
endif()
list(APPEND NAU_MINIMAL_DEPENDENCY_DIRS tinyimageformat)
list(APPEND NAU_MINIMAL_DEPENDENCY_TARGETS tinyimageformat)
if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../engine/3rdparty_libs/tinyimageformat/CMakeLists.txt")
  message(FATAL_ERROR "Missing demo runtime dependency: tinyimageformat. Restore recorded sources.")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/naudemo_sources.json" NAU_DEMO_SOURCE_MANIFEST)
foreach(module IN ITEMS CoreAssets CoreScene CoreAssetsCpu)
  string(JSON sourceCount LENGTH "${NAU_DEMO_SOURCE_MANIFEST}" sources ${module})
  math(EXPR lastSource "${sourceCount} - 1")
  set(NAU_DEMO_${module}_SOURCES)
  foreach(index RANGE ${lastSource})
    string(JSON source GET "${NAU_DEMO_SOURCE_MANIFEST}" sources ${module} ${index})
    set(absoluteSource "${CMAKE_CURRENT_LIST_DIR}/../${source}")
    if(NOT EXISTS "${absoluteSource}")
      message(FATAL_ERROR "Missing demo runtime source: ${source}. Restore recorded sources.")
    endif()
    list(APPEND NAU_DEMO_${module}_SOURCES "${absoluteSource}")
  endforeach()
endforeach()
