# Run before project() so unsuitable SDKs fail before compiler detection.
function(nau_check_emscripten_sdk)
    file(STRINGS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/emscripten-sdk-version.txt" expected)
    set(setup "Expected external emsdk ${expected}. Run emsdk install ${expected}, emsdk activate ${expected}, then dot-source emsdk_env.ps1. Use a fresh browser build directory.")
    if(NOT CMAKE_HOST_WIN32)
        message(FATAL_ERROR "The Nau browser build currently requires a Windows host. ${setup}")
    endif()
    if("$ENV{EMSDK}" STREQUAL "")
        message(FATAL_ERROR "EMSDK is missing. ${setup}")
    endif()
    file(TO_CMAKE_PATH "$ENV{EMSDK}/upstream/emscripten" sdk)
    set(toolchain "${sdk}/cmake/Modules/Platform/Emscripten.cmake")
    foreach(required "${toolchain}" "${sdk}/emcc.exe" "${sdk}/em++.exe")
        if(NOT EXISTS "${required}")
            message(FATAL_ERROR "Missing SDK file: ${required}. ${setup}")
        endif()
    endforeach()
    if(NOT EXISTS "${CMAKE_TOOLCHAIN_FILE}")
        message(FATAL_ERROR "Missing Emscripten toolchain; set CMAKE_TOOLCHAIN_FILE to ${toolchain}. ${setup}")
    endif()
    file(REAL_PATH "${toolchain}" expected_toolchain)
    file(REAL_PATH "${CMAKE_TOOLCHAIN_FILE}" actual_toolchain)
    if(NOT actual_toolchain STREQUAL expected_toolchain)
        message(FATAL_ERROR "Toolchain differs from active EMSDK: ${actual_toolchain}. ${setup}")
    endif()
    foreach(compiler emcc em++)
        execute_process(COMMAND "${sdk}/${compiler}.exe" --version
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors
            TIMEOUT 30)
        string(REGEX MATCH "Emscripten[^\n]*[ \t]([0-9]+\\.[0-9]+\\.[0-9]+)" identity "${output}")
        set(detected "${CMAKE_MATCH_1}")
        if(NOT result EQUAL 0 OR NOT identity OR NOT detected STREQUAL expected)
            message(FATAL_ERROR "Incompatible ${compiler}: detected '${detected}'. ${output}${errors} ${setup}")
        endif()
    endforeach()
    foreach(language C CXX)
        if(DEFINED CMAKE_${language}_COMPILER AND NOT CMAKE_${language}_COMPILER STREQUAL "")
            if(language STREQUAL "C")
                set(driver emcc)
            else()
                set(driver em++)
            endif()
            file(REAL_PATH "${CMAKE_${language}_COMPILER}" cached_compiler)
            file(REAL_PATH "${sdk}/${driver}.exe" expected_compiler)
            if(NOT cached_compiler STREQUAL expected_compiler)
                message(FATAL_ERROR "Native or incompatible compiler cache: ${cached_compiler}. ${setup}")
            endif()
        endif()
    endforeach()
    message(STATUS "Nau external Emscripten SDK: ${expected} (${sdk})")
endfunction()

nau_check_emscripten_sdk()
