# Resolve sample sources separately from the engine and preserve binary layout.
set(NAU_ENGINE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(NORMAL_PATH NAU_ENGINE_SOURCE_DIR)
if(NOT DEFINED NAU_SAMPLES_SOURCE_DIR)
  set(NAU_SAMPLES_SOURCE_DIR "${NAU_ENGINE_SOURCE_DIR}/../NauSamples" CACHE PATH "External NauSamples checkout")
endif()
get_filename_component(NAU_SAMPLES_SOURCE_DIR "${NAU_SAMPLES_SOURCE_DIR}" ABSOLUTE BASE_DIR "${NAU_ENGINE_SOURCE_DIR}")
set(NAU_SAMPLES_REQUIRED OFF)
if(NOT NAU_RUNTIME_PROFILE STREQUAL "demo" AND (NAU_CORE_SAMPLES OR NAU_DEMO_SOURCE_DIR))
  set(NAU_SAMPLES_REQUIRED ON)
  set(requiredSamples CMakeLists.txt)
  if(NAU_RUNTIME_PROFILE STREQUAL "minimal")
    list(APPEND requiredSamples minimalApp/CMakeLists.txt minimalApp/app_sample_main_min.cpp)
  else()
    list(APPEND requiredSamples sample_common/CMakeLists.txt sceneBase/CMakeLists.txt)
  endif()
  foreach(required IN LISTS requiredSamples)
    if(NOT EXISTS "${NAU_SAMPLES_SOURCE_DIR}/${required}")
      message(FATAL_ERROR "Missing required NauSamples input '${NAU_SAMPLES_SOURCE_DIR}/${required}'. Initialize NauSamples with git submodule update --init NauSamples from the parent Nau checkout, or set NAU_SAMPLES_SOURCE_DIR to a valid checkout.")
    endif()
  endforeach()
  message(STATUS "NauSamples source: ${NAU_SAMPLES_SOURCE_DIR}")
endif()
